name: gzdoom
title: GZDoom
base: core22
adopt-info: gzdoom # version is set based on the git tag we check out
summary: Doom Source Port
description: |
  Snap build from https://github.com/Hvassaa/gzdoom-snap
  To setup WADs, run the app once and put them in ~/snap/gzdoom/current/.config/gzdoom/
  ZDoom is a family of enhanced ports of the Doom engine for running on modern operating systems.
  It runs on Windows, Linux, and OS X, and adds new features not found in the games as originally
  published by id Software.
license: GPL-3.0
icon: snap/gui/gzdoom.png
source-code: "https://github.com/Hvassaa/gzdoom-snap"
grade: stable
confinement: strict

plugs:
  graphics-core22:
    interface: content
    target: $SNAP/graphics
    default-provider: mesa-core22

apps:
  gzdoom:
    command-chain:
      - bin/graphics-core22-wrapper
    command: usr/local/bin/gzdoom
    plugs:
      - opengl
      - x11
      - wayland
      - graphics-core22
      - desktop
      - desktop-legacy
      - audio-playback
    extensions:
      - kde-neon
    environment:
      KDE_FULL_SESSION: "false"

layout:
  /usr/local/share/games/doom:
    bind: $SNAP/usr/local/share/games/doom
  /usr/share/libdrm:
    bind: $SNAP/graphics/libdrm
  /usr/share/drirc.d:
    symlink: $SNAP/graphics/drirc.d

parts:
  gzdoom:
    source: https://github.com/ZDoom/gzdoom.git
    source-tag: 'g4.14.0'
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags --abbrev=10 | sed 's/^g//')
      patch $SNAPCRAFT_PART_SRC/src/d_iwad.cpp < $SNAPCRAFT_PROJECT_DIR/snap/local/location.patch # change "wad not found" path description
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DNO_FMOD=ON # only necessary for gzdoom < 3
      - -DZMUSIC_INCLUDE_DIR=$SNAPCRAFT_STAGE/usr/include
      - -DZMUSIC_LIBRARIES=$SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libzmusic.so
    build-packages:
      - g++
      - make
      - cmake
      - libsdl2-dev
      - zlib1g-dev
      - libbz2-dev
      - libjpeg-dev
      - libfluidsynth-dev
      - libgme-dev
      - libopenal-dev
      - libmpg123-dev
      - libsndfile1-dev
      - libgtk-3-dev
      - timidity
      - nasm
      - tar
      - libsdl1.2-dev
      - libglew-dev
      - libvpx-dev
    stage-packages:
      - kdialog
      - gxmessage
      - libsdl2-2.0-0
      - libvpx7
      - libgomp1
      - fluidsynth
      - libfluidsynth3
      - fluid-soundfont-gm
      - timidity
      - libopenal1
      - libmpg123-0
      - libsndfile1
      - qtwayland5
      - libaudio2
      - libgtk2.0-0
    after:
      - zmusic
  zmusic:
    source: https://github.com/ZDoom/ZMusic.git
    source-tag: '1.1.14'
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Release
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - g++
    stage-packages:
      - libasound2
  graphics-core22:
    after:
      - gzdoom
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/graphics-core22-cleanup mesa-core22 nvidia-core22
    prime:
    - bin/graphics-core22-wrapper
